# hyperparameters.yaml
model:
  name: CamoXpert-S
  backbone: edgenext_small
  num_experts: 3
  stage_dims: [48, 96, 160, 256]

training:
  batch_size: 8
  accumulation_steps: 2
  epochs: 100
  early_stopping_patience: 15

optimizer:
  type: AdamW
  learning_rate: 0.0001
  weight_decay: 0.00001
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  type: cosine
  warmup_epochs: 5
  t_0: 10
  t_mult: 2

loss_weights:
  bce: 0.3
  dice: 0.3
  structure: 0.4

augmentation_probs:
  geometric: 0.5
  color: 0.3
  camouflage: 0.4
  noise: 0.2